### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by canadaduane** [unframework/tile-game#20]
Just trying to see what you've built here, it looks really neat!

Not sure if I'm doing something wrong... I cloned and ran `yarn install` then `yarn start`:

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/129/96951939-e42bbe80-14aa-11eb-8aff-e9eca070046e.png">

I was able to get around above error by moving the asset to the public dir, but then there are further errors regarding `useIrradianceRenderer` not being found.

**Comment by unframework** [comment]
Hey, thanks for checking out the repo!

I just added a type declaration for *.glb files, maybe that will fix the error above. Not sure what to say about the `useIrradianceRenderer` error - I did a fresh check-out here and `yarn start` seems to work. If it still happens on latest master, mind reporting that trace as well?

And I need to add a screenshot in README, hehe. Here is a short overview post with pictures: https://unframework.com/portfolio/simple-global-illumination-lightmap-baker-for-threejs/.

**Comment by canadaduane** [comment]
Looks like that fixed the glb file issue!

Here is what I'm seeing after that:

```
Failed to compile.

/Users/duane/tmp/threejs-lightmap-baker/src/IrradianceKeyframeRenderer.tsx
TypeScript error in /Users/duane/tmp/threejs-lightmap-baker/src/IrradianceKeyframeRenderer.tsx(4,10):
Module '"../../../../../Users/duane/tmp/threejs-lightmap-baker/src/IrradianceRenderer"' has no exported member 'useIrradianceRenderer'. Did you mean to use 'import useIrradianceRenderer from "../../../../../Users/duane/tmp/threejs-lightmap-baker/src/IrradianceRenderer"' instead?  TS2614

    2 | import * as THREE from 'three';
    3 |
  > 4 | import { useIrradianceRenderer } from './IrradianceRenderer';
      |          ^
    5 |
    6 | export function useIrradianceKeyframeRenderer(
    7 |   factorName: string,
```

When I look at `IrradianceRenderer.tsx`, I don't see `useIrradianceRenderer` being declared or exported anywhere (maybe it's supposed to be autogenerated?)

**Comment by unframework** [comment]
Good catch, that `IrradianceKeyframeRenderer.tsx` file is not even used anymore. I updated the code accordingly.

It is quite odd that my create-react-app does not complain about TypeScript errors - must be something on my end then.

**Comment by canadaduane** [comment]
More progress! :)

Now I see this:
```
Failed to compile.

/Users/duane/tmp/threejs-lightmap-baker/src/App.tsx
TypeScript error in /Users/duane/tmp/threejs-lightmap-baker/src/App.tsx(15,47):
Cannot find module './IrradianceKeyframeRenderer'.  TS2307

    13 | import IrradianceRenderer from './IrradianceRenderer';
    14 | import { PROBE_BATCH_COUNT } from './IrradianceLightProbe';
  > 15 | import { useIrradianceKeyframeRenderer } from './IrradianceKeyframeRenderer';
       |                                               ^
    16 | import IrradianceCompositor from './IrradianceCompositor';
    17 | import SceneControls from './SceneControls';
    18 | import GridGeometry from './GridGeometry';
```

**Comment by unframework** [comment]
Ok, I removed that one as well. Hopefully it works!

**Comment by canadaduane** [comment]
Bingo! Demo is working. Thank you.

FYI: there are more Typescript/ESLint warnings, but none were blockers (e.g. "defined but never used").
